# Generated by Django 3.0.2 on 2020-03-29 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geosystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
