# Generated by Django 3.0.2 on 2020-03-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosystem', '0006_globalcovid19liveshp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='globalCovid19LiveShp',
            new_name='globalCovid19Live',
        ),
    ]
