# Generated by Django 3.0.2 on 2020-03-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosystem', '0010_auto_20200329_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldbiospheres',
            name='review',
            field=models.CharField(default='review later', max_length=254),
        ),
    ]
