# Generated by Django 3.0.2 on 2020-03-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosystem', '0012_auto_20200330_0025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='CityWeather',
        ),
    ]
