# Generated by Django 2.2 on 2020-04-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosystem', '0013_auto_20200330_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityweather',
            options={},
        ),
    ]
