# -*- coding: utf-8 -*-
from odoo import models, fields, api, _ 
class Calendar(models.Model):
    _name = 'governance.calendar'
    _description = 'Calendar Model'
    calendar_date = fields.Date()
    calendar_date_string = fields.Char()
    calendar_month = fields.Integer('Month')
    calendar_day = fields.Integer('Day')
    calendar_year = fields.Integer('Year')
    calendar_quarter = fields.Integer()
    day_of_week_in_month = fields.Integer()
    day_of_week_in_year = fields.Integer()
    day_of_week_in_quarter = fields.Integer()
    day_of_quarter = fields.Integer()
    day_of_year = fields.Integer()
    week_of_month = fields.Integer()
    week_of_quarter = fields.Integer()
    week_of_year = fields.Integer()
    month_name = fields.Char('Month')
    first_date_of_week = fields.Date()
    last_date_of_week = fields.Date()
    first_date_of_month = fields.Date()
    last_date_of_month = fields.Date()
    first_date_of_quarter = fields.Date()
    last_date_of_quarter = fields.Date()
    first_date_of_year = fields.Date()
    last_date_of_year = fields.Date()
    is_holiday = fields.Boolean()
    is_holiday_season = fields.Boolean()
    holiday_name = fields.Char()
    holiday_season_name = fields.Char()
    is_weekday = fields.Boolean()
    previous_business_day = fields.Date()
    next_business_day = fields.Date()
    is_leap_year = fields.Boolean()
    days_in_month = fields.Integer()
    isActive = fields.Boolean()
    isBusinessDay = fields.Boolean()
    created_by = fields.Many2one('hr.employee')
    create_day = fields.Date()
    updated_by = fields.Many2one('hr.employee')
    updated_day = fields.Date()
  