# Generated by Django 3.0.2 on 2020-03-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosystem', '0003_auto_20200329_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incidences',
            new_name='Incidence',
        ),
    ]
