# Generated by Django 3.0.2 on 2020-03-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosystem', '0004_auto_20200329_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
