# Generated by Django 3.0.2 on 2020-03-29 15:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosystem', '0005_incidence_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='globalCovid19LiveShp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('objectid', models.FloatField()),
                ('country_re', models.CharField(max_length=254)),
                ('last_updat', models.FloatField()),
                ('lat', models.FloatField()),
                ('long_field', models.FloatField()),
                ('confirmed', models.FloatField()),
                ('deaths', models.FloatField()),
                ('recovered', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
