# Generated by Django 3.0.2 on 2020-03-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosystem', '0008_worldbiospheresshp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldbiospheresshp',
            name='review',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
