# Generated by Django 3.0.2 on 2020-01-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_auto_20200125_0651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fields',
            new_name='Field',
        ),
    ]
